Description: >

  This template deploys an EC2 based static website in AWS cloud environment.

  Last Modified: 17th March 2020
  Author: Rajnish Srivastava

Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/rajnishsrivastava/aws-ec2-static-website-template/infrastructure/vpc.yaml
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        VpcCIDR: 10.0.0.0/16
        PublicSubnet1CIDR: 10.0.1.0/24
        PublicSubnet2CIDR: 10.0.2.0/24
        PrivateSubnet1CIDR: 10.0.3.0/24
        PrivateSubnet2CIDR: 10.0.4.0/24

  SecurityGroups:
     Type: AWS::CloudFormation::Stack
     Properties:
       TemplateURL: https://s3.amazonaws.com/rajnishsrivastava/aws-ec2-static-website-template/infrastructure/security-groups.yaml
       Parameters:
         EnvironmentName: !Ref AWS::StackName
         VPC: !GetAtt VPC.Outputs.VPC

  Application:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/rajnishsrivastava/aws-ec2-static-website-template/infrastructure/application.yaml
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        InstanceType: t2.micro
        MinClusterSize: 1
        MaxClusterSize: 1
        VPC: !GetAtt VPC.Outputs.VPC
        EC2HostSecurityGroup: !GetAtt SecurityGroups.Outputs.EC2HostSecurityGroup
        LoadBalancerSecurityGroup: !GetAtt SecurityGroups.Outputs.LoadBalancerSecurityGroup
        PublicSubnets: !GetAtt VPC.Outputs.PublicSubnets
        PrivateSubnets: !GetAtt VPC.Outputs.PrivateSubnets
        OperatorEMail: awstestmail@yopmail.com
        KeyName: mykeypair

Outputs:
  WebsiteServiceUrl:
     Description: The URL endpoint for the website
     Value: !GetAtt Application.Outputs.URL